Repository King-Pollack/web, pull requests merged in 2023-12, with the labels that each got.

#6 [self] Feature/entity 연관관계 매핑
  src/main/java/com/king/app/domain/reserve/ReserveLog.java
  src/main/java/com/king/app/domain/type/Route.java
  src/main/java/com/king/app/domain/type/Status.java
  src/main/java/com/king/app/domain/user/User.java
  src/main/java/com/king/app/domain/waiting/WaitingLog.java
Labels: enhancement

#8 Feature/entity 연관관계매핑
  src/main/java/com/king/app/domain/reserve/ReservationLog.java
  src/main/java/com/king/app/domain/type/AccessRoute.java
  src/main/java/com/king/app/domain/type/ReservationStatus.java
  src/main/java/com/king/app/domain/type/UserAgeRange.java
  src/main/java/com/king/app/domain/type/UserGender.java
  src/main/java/com/king/app/domain/user/User.java
  src/main/java/com/king/app/domain/waiting/WaitingLog.java
Labels: enhancement

#12 Feature/ageRange 타입 변경, nickname 추가
  src/main/java/com/king/app/domain/user/User.java
Labels: refactor

#15 Feature/enum type 설정 및 테스트 추가
  src/main/java/com/king/app/domain/user/User.java
  src/test/java/com/king/app/domain/user/UserEnumTest.java
Labels: enhancement

#18 Feature/project conf
  build.gradle
  src/main/java/com/king/app/AppApplication.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#21 Feature/kakao login
  build.gradle
  src/main/java/com/king/app/AppApplication.java
  src/main/java/com/king/app/common/config/WebSecurityConfig.java
  src/main/java/com/king/app/common/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/king/app/common/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/king/app/common/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/king/app/common/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/king/app/common/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/king/app/common/oauth2/userinfo/PrincipalDetails.java
  src/main/java/com/king/app/domain/type/UserAgeRange.java
  src/main/java/com/king/app/domain/type/UserGender.java
  src/main/java/com/king/app/domain/user/User.java
  src/main/java/com/king/app/domain/user/UserAgeRangeConverter.java
  src/main/java/com/king/app/infrastructure/repository/user/UserRepository.java
  src/main/java/com/king/app/presentation/web/waiting/WaitingController.java
  src/main/resources/templates/admin/layout/headbar.html
  src/main/resources/templates/admin/layout/sidebar.html
  src/main/resources/templates/admin/waiting-board.html
  src/main/resources/templates/waiting/layout/headbar.html
  src/main/resources/templates/waiting/layout/header.html
  src/main/resources/templates/waiting/layout/sidebar.html
  src/main/resources/templates/waiting/waiting-login.html
  src/main/resources/templates/waiting/waiting-view.html
  src/main/resources/templates/wating/waiting-view.html
  src/test/java/com/king/app/domain/user/UserEnumTest.java
Labels: enhancement

#25 [#23] refactor : DT 컬럼 자동 업데이트 기능추가 .
  src/main/java/com/king/app/AppApplication.java
  src/main/java/com/king/app/domain/reserve/ReservationLog.java
  src/main/java/com/king/app/domain/user/User.java
  src/main/java/com/king/app/domain/waiting/WaitingLog.java
Labels: enhancement

#27 Feature/stand redis config
  src/main/java/com/king/app/AppApplication.java
  src/main/java/com/king/app/common/config/RedisCacheConfig.java
  src/main/java/com/king/app/common/config/RedisDBConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#37 [self] Feature/대기하기 log 저장 db
  src/main/java/com/king/app/application/waiting/PartySizeServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitTimeServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingEntryServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingLogServiceImpl.java
  src/main/java/com/king/app/infrastructure/mapper/WaitingMapper.java
  src/main/resources/mapper/WaitingMapper.xml
Labels: refactor

#36 Feature/대기하기 log 저장 db
  src/main/java/com/king/app/application/waiting/PartySizeService.java
  src/main/java/com/king/app/application/waiting/PartySizeServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitTimeService.java
  src/main/java/com/king/app/application/waiting/WaitTimeServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingEntryService.java
  src/main/java/com/king/app/application/waiting/WaitingEntryServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingLogService.java
  src/main/java/com/king/app/application/waiting/WaitingLogServiceImpl.java
  src/main/java/com/king/app/application/waiting/dto/WeekDateTimeDto.java
  src/main/java/com/king/app/domain/waiting/WaitingLog.java
  src/main/java/com/king/app/infrastructure/mapper/WaitingMapper.java
  src/main/java/com/king/app/infrastructure/repository/waiting/WaitingLogRepository.java
  src/main/java/com/king/app/presentation/api/waiting/controller/PartySizeAnalyticsController.java
  src/main/java/com/king/app/presentation/api/waiting/controller/WaitTimeAnalyticsController.java
  src/main/java/com/king/app/presentation/api/waiting/controller/WaitingEntryAnalyticsController.java
  src/main/resources/mapper/WaitingMapper.xml
Labels: enhancement

#40 Bugfix/팀 인원 주간 통계 로직 null 처리 추가
  src/main/java/com/king/app/application/waiting/PartySizeServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingEntryServiceImpl.java
Labels: bug, refactor

#41 [self] 리뷰 반영 error log로 수정
  src/main/java/com/king/app/application/waiting/PartySizeServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingEntryServiceImpl.java
Labels: refactor

#34 Feature/waiting redis
  src/main/java/com/king/app/application/waiting/RedisWaitingService.java
  src/main/java/com/king/app/application/waiting/WaitingService.java
  src/main/java/com/king/app/common/config/WebSecurityConfig.java
  src/main/java/com/king/app/common/oauth2/userinfo/PrincipalDetails.java
  src/main/java/com/king/app/domain/waiting/WaitingTeam.java
  src/main/java/com/king/app/infrastructure/repository/waiting/RedisWaitingRepository.java
  src/main/java/com/king/app/infrastructure/repository/waiting/WaitingRepository.java
  src/main/java/com/king/app/presentation/api/waiting/WaitingAPIController.java
  src/main/java/com/king/app/presentation/api/waiting/request/WaitingTeamRequest.java
  src/main/java/com/king/app/presentation/api/waiting/response/WaitingTeamResponse.java
  src/main/resources/application.yml
  src/main/resources/templates/waiting/layout/header.html
  src/main/resources/templates/waiting/waiting-login.html
  src/main/resources/templates/waiting/waiting-view.html
Labels: enhancement

#54 Feature/queue update sse
  src/main/java/com/king/app/application/waiting/RedisWaitingService.java
  src/main/java/com/king/app/application/waiting/RedisWaitingStreamService.java
  src/main/java/com/king/app/application/waiting/WaitingSSEService.java
  src/main/java/com/king/app/application/waiting/WaitingSSEServiceImpl.java
  src/main/java/com/king/app/application/waiting/WaitingService.java
  src/main/java/com/king/app/application/waiting/WaitingStreamService.java
  src/main/java/com/king/app/common/config/WebSecurityConfig.java
  src/main/java/com/king/app/domain/type/UserAgeRange.java
  src/main/java/com/king/app/domain/type/UserGender.java
  src/main/java/com/king/app/infrastructure/repository/waiting/RedisWaitingRepository.java
  src/main/java/com/king/app/infrastructure/repository/waiting/WaitingRepository.java
  src/main/java/com/king/app/presentation/api/waiting/WaitingAPIController.java
  src/main/java/com/king/app/presentation/api/waiting/WaitingSSEController.java
  src/main/resources/static/js/waiting-login.js
  src/main/resources/static/js/waiting.js
  src/main/resources/templates/waiting/layout/header.html
  src/main/resources/templates/waiting/waiting-login.html
  src/main/resources/templates/waiting/waiting-view.html
Labels: enhancement
